name: "변수로 계산기 만들기"

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  calculate1:
    runs-on: ubuntu-latest
    env:
      NUMBER1: 12
      NUMBER2: 35
    steps:
      - name: Calculate
        uses: actions/github-script@v6
        with:
          script: |
            const number1 = parseInt(process.env.NUMBER1);
            const number2 = parseInt(process.env.NUMBER2);
            const result = number1 + number2;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '계산기 1',
              body: `${number1} + ${number2} = ${result}`
            })

  calculate2:
    runs-on: ubuntu-latest
    env:
      NUMBER1: ${{ vars.NUMBER1 }}
      NUMBER2: ${{ vars.NUMBER2 }}
    steps:
      - name: Print
        run: |
          echo "${NUMBER1} ${NUMBER2}"
      - name: Calculate
        uses: actions/github-script@v6
        with:
          script: |
            const number1 = parseInt(process.env.NUMBER1);
            const number2 = parseInt(process.env.NUMBER2);
            const result = number1 + number2;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '계산기 2',
              body: `${number1} + ${number2} = ${result}`
            })